### ISSUE TITLE
MemoryError when run pubmed dataset

### ISSUE THREAD

**Issue by Abigale001** [Blei-Lab/online-hdp#4]
When I run pubmed dataset, it raises memory error. 
It shows:
`creating directory pubmed/corpus-pubmed-kappa-0.5-tau-1-batchsize-100`
`creating online hdp instance.`
`T = 300, K = 20, D = 8200000, W = 737869083`
`Traceback (most recent call last):`
`  File "../run_online_hdp.py", line 262, in <module> run_online_hdp()`
`  File "../run_online_hdp.py", line 138, in run_online_hdp options.adding_noise)`
`  File "/home/nlp/topic/online-hdp-master/onlinehdp.py", line 184, in __init__ self.m_lambda = np.random.gamma(1.0, 1.0, (T, W)) * D*100/(T*W)-eta`
`  File "mtrand.pyx", line 2233, in mtrand.RandomState.gamma (numpy/random/mtrand/mtrand.c:20292)`
`  File "mtrand.pyx", line 234, in mtrand.cont2_array_sc (numpy/random/mtrand/mtrand.c:3092)`
`MemoryError`
But my memory is 250G. 
Anyone knows why?

**Comment by Abigale001** [comment]
It's my fault.
The vocabulary in pubmed is 141043.
How important it is to communicate with other students!
